#define UNEQUALSOFTENINGS 
#define MULTIPLEDOMAINS 16
#define TOPNODEFACTOR 3.0
#define PEANOHILBERT 
#define WALLCLOCK 
#define AUTO_SWAP_ENDIAN_READIC 
#define DOUBLEPRECISION 2
#define OVERRIDE_STOP_FOR_SUBOPTIMUM_DOMAINS 
#define NO_ISEND_IRECV_IN_DOMAIN 
